runtime: python311

entrypoint: gunicorn app:app --bind :$PORT --workers 4 --threads 2 --timeout 120

env_variables:
  FLASK_ENV: 'production'
  DATABASE_PATH: 'housing_database.db'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
