name: "🌟 مشكلة مناسبة للمبتدئين - Good First Issue"
description: "قضية مناسبة للمساهمين الجدد - Issue suitable for new contributors"
title: "[Good First Issue]: "
labels: ["good first issue", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        مرحباً بك في نظام إدارة الإسكان الجامعي! 🎉
        Welcome to the University Housing Management System! 🎉
        
        هذا النموذج مخصص لإنشاء قضايا مناسبة للمساهمين الجدد.
        This template is for creating issues suitable for new contributors.

  - type: textarea
    id: description
    attributes:
      label: "وصف المهمة - Task Description"
      description: "وصف واضح ومختصر للمهمة - A clear and concise description of the task"
      placeholder: "نحتاج إلى إضافة زر لطباعة التقارير..."
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: "معايير القبول - Acceptance Criteria"
      description: "ما الذي يجب تحقيقه؟ - What needs to be accomplished?"
      placeholder: |
        - [ ] إضافة زر الطباعة
        - [ ] تنسيق الصفحة للطباعة
        - [ ] اختبار الطباعة
    validations:
      required: true

  - type: textarea
    id: guidance
    attributes:
      label: "إرشادات للمبتدئين - Guidance for Beginners"
      description: "إرشادات ونصائح للمساهمين الجدد - Guidance and tips for new contributors"
      placeholder: |
        ملفات العمل: static/reports.html
        مراجع مفيدة: print_styles.css
        خطوات مقترحة:
        1. افتح الملف...
        2. أضف الكود...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: "المكون - Component"
      description: "أي جزء من النظام؟ - Which part of the system?"
      options:
        - "واجهة المستخدم - UI"
        - "قاعدة البيانات - Database"
        - "التوثيق - Documentation"
        - "الاختبارات - Tests"
        - "أخرى - Other"
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: "مستوى الصعوبة - Difficulty Level"
      description: "مستوى صعوبة المهمة - Task difficulty level"
      options:
        - "سهل جداً - Very Easy"
        - "سهل - Easy"
        - "متوسط - Medium"
    validations:
      required: true

  - type: dropdown
    id: time
    attributes:
      label: "الوقت المتوقع - Estimated Time"
      description: "الوقت المتوقع للإنجاز - Estimated time to complete"
      options:
        - "أقل من ساعة - Less than 1 hour"
        - "1-2 ساعة - 1-2 hours"
        - "2-4 ساعات - 2-4 hours"
        - "4-8 ساعات - 4-8 hours"
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: "الموارد المفيدة - Helpful Resources"
      description: "روابط ومراجع مفيدة - Helpful links and references"
      placeholder: |
        - [Flask Documentation](https://flask.palletsprojects.com/)
        - [Python Style Guide](https://pep8.org/)
      render: markdown

  - type: textarea
    id: mentor
    attributes:
      label: "ملاحظات للمرشد - Mentor Notes"
      description: "ملاحظات إضافية لمن سيشرف على المساهم - Additional notes for the mentor"
      placeholder: "هذه المهمة مناسبة لمن لديه معرفة أساسية بـ HTML/CSS"

  - type: checkboxes
    id: prerequisites
    attributes:
      label: "المتطلبات الأساسية - Prerequisites"
      description: "ما هي المهارات المطلوبة؟ - What skills are required?"
      options:
        - label: "معرفة أساسية بـ Python - Basic Python knowledge"
        - label: "معرفة أساسية بـ HTML/CSS - Basic HTML/CSS knowledge"
        - label: "معرفة أساسية بـ Git - Basic Git knowledge"
        - label: "معرفة أساسية بـ Flask - Basic Flask knowledge"
        - label: "لا يوجد متطلبات خاصة - No special requirements"
